# general build configuration
[build]
base = "web/"
publish = "public/"
command = "npm run build:pro"

# redirect from www.docedados.com
[[redirects]]
from = "https://www.docedados.com/*"
to = "https://docedados.com/:splat"
status = 301
force = true
